# config/packages/security.yaml
security:
    encoders:
        # this internal class is used by Symfony to represent in-memory users
        Symfony\Component\Security\Core\User\User: 'bcrypt'
        App\Entity\User:
            algorithm: bcrypt
    providers:
        backend_users:
            memory:
                users:
                    admin: { password: '$2y$13$Dk8BDE8QFcLG2yceNbQt7O45E/AIvg60AZQzpmvXQ1chafHPrVidu', roles: ['ROLE_ADMIN'] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: /login
                failure_path: /login
            guard:
                authenticators:
                    - App\Security\CustomAuthAuthenticator
            logout:
                path: app_logout
                target: /login
                invalidate_session: true
